CREATE TABLE CATEGORYS
(
ID INT PRIMARY KEY IDENTITY,
NAME VARCHAR(70) NOT NULL UNIQUE
)

CREATE TABLE CLIENTS
(
ID INT PRIMARY KEY IDENTITY,
NAME VARCHAR(70) NOT NULL,
CPF CHAR(11) NOT NULL UNIQUE,
CEP CHAR(8) NOT NULL,
BIRTHDATE DATETIME2 NOT NULL,
PHONENUMBER CHAR(11) NOT NULL
)	

CREATE TABLE RESTAURANTS 
(
ID iNT PRIMARY KEY IDENTITY,
NAME VARCHAR(70) NOT NULL UNIQUE,
CNPJ CHAR(14) NOT NULL UNIQUE,
PHONENUMBER CHAR(11) NOT NULL
)

CREATE TABLE USERS 
(
ID iNT PRIMARY KEY IDENTITY,
EMAIL VARCHAR(70) NOT NULL UNIQUE,
PASSWORD VARCHAR(50) NOT NULL,
RESTAURANTID INT NOT NULL REFERENCES RESTAURANTS,
CLIENTID INT NOT NULL REFERENCES CLIENTS
)

CREATE TABLE PLATES 
(
ID iNT PRIMARY KEY IDENTITY,
NAME VARCHAR(70) NOT NULL,
DESCRIPTION VARCHAR(100) NOT NULL,
PRICE FLOAT NOT NULL,
CATEGORYID INT NOT NULL REFERENCES CATEGORYS,
RESTAURANTID INT NOT NULL REFERENCES RESTAURANTS
)

CREATE TABLE ORDERS 
(
ID INT PRIMARY KEY IDENTITY,
STATUS INT NOT NULL,
CLIENTID INT NOT NULL REFERENCES CLIENTS,
RESTAURANTID INT NOT NULL REFERENCES RESTAURANTS
)

CREATE TABLE ORDER_ITEMS
(
ORDERID INT NOT NULL REFERENCES ORDERS,
PLATEID INT NOT NULL REFERENCES PLATES, 
AMOUNT INT NOT NULL,
TOTAL FLOAT NOT NULL, 
PRIMARY KEY (ORDERID)
)



























